[package]
name = "wmclient"
version = "0.1.0"
authors = ["Andrea Castello <support@scientiamobile.com>"]
edition = "2018"

[dependencies]
ureq = { version = "*", features = ["json", "charset"] }
lru = "0.6.6"
serde = { version = "1.0.130", features = ["derive"]}
thiserror = "1.0"